import { discoverApi, buildCatalog, headers } from './providers.js';
import { inferProvider } from './config.js';
const OPENAI_RESPONSES='https://api.openai.com/v1/responses';
const OPENAI_IMAGES='https://api.openai.com/v1/images/generations';
const OPENAI_EDITS='https://api.openai.com/v1/images/edits';
const OPENROUTER_CHAT='https://openrouter.ai/api/v1/chat/completions';
const OPENROUTER_IMAGES='https://openrouter.ai/api/v1/images';
export async function discoverApis(apis){const results=await Promise.all(apis.filter(a=>a.enabled!==false).map(a=>discoverApi({...a,provider:inferProvider(a)||a.provider})));const catalog=buildCatalog(results);catalog._apis=results.filter(x=>x.alive);return{results,catalog};}
async function requestJson(url,api,body,provider){const response=await fetch(url,{method:'POST',headers:headers(api,provider),body:JSON.stringify(body)});const data=await response.json().catch(()=>({}));if(!response.ok){const e=new Error(data?.error?.message||`HTTP ${response.status}`);e.status=response.status;e.details=data;throw e;}return data;}
async function openAiEdit(api,model,prompt,imageData){const match=imageData.match(/^data:([^;]+);base64,(.+)$/);if(!match)throw new Error('Invalid image data.');const form=new FormData();form.append('model',model);form.append('prompt',prompt);form.append('image',new Blob([Buffer.from(match[2],'base64')],{type:match[1]}),'input.png');const response=await fetch(OPENAI_EDITS,{method:'POST',headers:{Authorization:`Bearer ${api.key}`},body:form});const data=await response.json().catch(()=>({}));if(!response.ok){const e=new Error(data?.error?.message||`HTTP ${response.status}`);e.status=response.status;e.details=data;throw e;}return data;}
export async function chat(catalog,message,imageData){const choice=imageData?catalog.selected.vision:catalog.selected.chat;if(!choice)throw new Error(imageData?'No working vision model was discovered.':'No working chat model was discovered.');const api=catalog._apis.find(x=>x.id===choice.apiId);if(!api)throw new Error('Selected API key is unavailable.');if(choice.provider==='openrouter'){const content=imageData?[{type:'text',text:message},{type:'image_url',image_url:{url:imageData}}]:message;const d=await requestJson(OPENROUTER_CHAT,api,{model:choice.id,messages:[{role:'user',content}]},'openrouter');return{answer:d?.choices?.[0]?.message?.content||'',...choice};}const input=imageData?[{role:'user',content:[{type:'input_text',text:message},{type:'input_image',image_url:imageData}]}]:message;const d=await requestJson(OPENAI_RESPONSES,api,{model:choice.id,input},'openai');return{answer:d?.output_text||'',...choice};}
export async function generateImage(catalog,prompt,imageData){const choice=catalog.selected.image;if(!choice)throw new Error('No working image-generation model was discovered.');const api=catalog._apis.find(x=>x.id===choice.apiId);if(!api)throw new Error('Selected image API key is unavailable.');let d;if(choice.provider==='openrouter')d=await requestJson(OPENROUTER_IMAGES,api,{model:choice.id,prompt,...(imageData?{input_references:[{type:'image_url',image_url:{url:imageData}}]}:{})},'openrouter');else d=imageData?await openAiEdit(api,choice.id,prompt,imageData):await requestJson(OPENAI_IMAGES,api,{model:choice.id,prompt},'openai');const item=d?.data?.[0];const image=item?.b64_json?`data:${item.media_type||'image/png'};base64,${item.b64_json}`:item?.url||null;if(!image)throw new Error('Image model returned no image.');return{image,...choice};}
